train_args:
  num_epochs: 5
  learning_rate: 5.0e-4
  adam_beta1: 0.9
  adam_beta2: 0.98
  weight_decay: 1.0e-5
  eps: 1.0e-6
  max_grad_norm: 0.0
  schedule_type: "linear"
  gradient_accumulation_steps: 1 

  warmup_steps: null
  warmup_pct: 0.06
  cooldown_steps: null
  checkpoint: null

  wandb: true
  wandb_project_name: "bert"
  wandb_entity: "gpt4all"

  log_grads_every: 100
  log_lr_every: 10
  save_every: 20000
  eval_every: 500
  output_dir: "ckpts/mlm-trainer"
  # if using deepspeed, this will be ignored
  pretrained: null
  pooling: "last"
  use_fp8: false

model_args:
  "model_type": "mlm"
  seq_len: 128
  rotary_emb_fraction: 1.0
  pad_vocab_to_multiple_of: 64 
  use_rms_norm: false
  activation_function: "swiglu"
  tokenizer_name: "bert-base-uncased"
  model_name: "bert-base-uncased"
  qkv_proj_bias: false
  mlp_fc1_bias: false
  mlp_fc2_bias: false
  attn_pdrop: 0.0
  gradient_checkpointing: false

mlm_data_args:
  tokenized_dataset: "nomic-ai/bert-128-grouped"
  workers: 4
  batch_size: 4096
  seed: 42
  shuffle: true
  mlm_prob: 0.30
  val_mlm_prob: 0.15
  val_pct: 0.01